apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  pkey: UjRYT0U4MEstU05GUFZGQUQtNlM5MzZUSFktODlYWUtXQzE=
  psec: MmViNDA4ZTc0MTkyODc1MjhhNjI4MjFiNDgyMTA5NDUwZjdhZWIyZWYxMjNhMGZiYzE4MDYyOTdjM2RhNzFjZGY3OWJjYjNlYTM2YjZjMWI1NDliYmQ3ZDk3MDQ5M2M0NmU4YTIzMjEyYjAyNDQxNTc4MWE4Y2NlOWIzZjkzNTM=
