apiVersion: v1
kind: ConfigMap
metadata:
  name: authsvc-config
data:
  auth-config.edn: |
    {:sso {:url "sso-url"}
    :threescale {:url "threescale-url"
              :api-access-token "threescale provider access token"
              :role-section {"name of realm role in SSO with access to sections" ["portal" "monitoring" "plans" "partner"]
}}}
